### ISSUE TITLE
APL calculation bug

### ISSUE THREAD

**Issue by davidRFB** [FATSLiM/fatslim#16]
Hi ! 

I am using FATSLiM to calculate the APL of a system with 15 % of Ligands into a membrane of DMPG. 

but this problem came out ! 

fatslim apl --t ../traj_comp.xtc --conf ../step7_0ns.gro --index fat_ndx.ndx  --plot-apl PLOT_APL
FATSLiM - Fast Analysis Toolbox for Simulations of Lipid Membranes
version 0.2.2
Copyright (c) 2013-2016 Sébastien Buchoux

Running command: 'apl'... This may take some time, be patient!
Analysis will be performed using 4 threads.

FATAL ERROR: b'headgroups'

Well, this was unexpected... Congrats, you probably found a bug in FATSLiM!
Please report the following traceback to the devs:

Traceback (most recent call last):
  File "/home/david/anaconda3/lib/python3.7/site-packages/fatslimlib/__init__.py", line 132, in main
    exit_code = _command_registry.run(argv)
  File "/home/david/anaconda3/lib/python3.7/site-packages/fatslimlib/command.py", line 211, in run
    cmd_obj.run_with_args(command_args)
  File "/home/david/anaconda3/lib/python3.7/site-packages/fatslimlib/command.py", line 405, in run_with_args
    self._run()
  File "/home/david/anaconda3/lib/python3.7/site-packages/fatslimlib/command.py", line 477, in _run
    nframes = super(AnalyticalCommand, self)._run()
  File "/home/david/anaconda3/lib/python3.7/site-packages/fatslimlib/command.py", line 360, in _run
    output = self.run()
  File "/home/david/anaconda3/lib/python3.7/site-packages/fatslimlib/command.py", line 528, in run
    self.initialize_trajetory(traj)
  File "/home/david/anaconda3/lib/python3.7/site-packages/fatslimlib/command.py", line 489, in initialize_trajetory
    interacting_group=self.namespace.interacting_group)
  File "fatslimlib/core_base.pyx", line 1779, in fatslimlib.core_base.Trajectory.initialize
  File "fatslimlib/core_base.pyx", line 1296, in fatslimlib.core_base.IndexReader.__getitem__
KeyError: b'headgroups'

Sorry, I made a boo boo...

Thanks for your time and consideration! 

Best Regards 
David

**Comment by sizeineb** [comment]
Hi David, 

I am having the same error message when using FATSLiM to calculate membrane thickness. Did you manage to fix the problem? 

Best, 
Zeineb

**Comment by sizeineb** [comment]
I found the problem. The parameter --hg-group should be specified if the headgroups in the index file were not renamed. We have to specify the name of the group to use in the index file with the option --hg-group.
