### ISSUE TITLE
fatslim install

### ISSUE THREAD

**Issue by clarkea07** [FATSLiM/fatslim#17]
I tried installing fatslim both with pip and by cloning from git, and I get the following error message:

Traceback (most recent call last):
  File "/usr/local/bin/fatslim", line 4, in <module>
    __import__('pkg_resources').run_script('fatslim==0.2.2', 'fatslim')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1436, in run_script
    source = open(script_filename).read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 179: ordinal not in range(128)

Do you know how to resolve this?

**Comment by seb-buch** [comment]
Hi,

I can not reproduce this issue. I need some further information:
what is your OS? Python version? are you using conda? what is the exact pip command you used?

Thanks
