### ISSUE TITLE
Bicelle systems: Index error

### ISSUE THREAD

**Issue by poojari1** [FATSLiM/fatslim#18]
Hi,

I am trying to run APL anaylsis for bicelle system simulated with martini ff and fatslim fails with the below error. The tool and command works perfectly for flat bilayer systems. Please can I know if there is a fix to this isssue. In the bicelle setup, i have short DHPC lipids at the rim and lipids flip flop at the edges of the rim.  

command: fatslim apl -c 0ns.gro -n index.ndx -t nowat.xtc -b 500000 --plot-apl dopc_bicelle_apl.xvg --plot-area dopc_bicelle_area.xvg --hg-group DOPC_PO4

error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fatslim-0.2.1-py3.6-linux-x86_64.egg/fatslimlib/__init__.py", line 132, in main
    exit_code = _command_registry.run(argv)
  File "/usr/local/lib/python3.6/dist-packages/fatslim-0.2.1-py3.6-linux-x86_64.egg/fatslimlib/command.py", line 211, in run
    cmd_obj.run_with_args(command_args)
  File "/usr/local/lib/python3.6/dist-packages/fatslim-0.2.1-py3.6-linux-x86_64.egg/fatslimlib/command.py", line 405, in run_with_args
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/fatslim-0.2.1-py3.6-linux-x86_64.egg/fatslimlib/command.py", line 477, in _run
    nframes = super(AnalyticalCommand, self)._run()
  File "/usr/local/lib/python3.6/dist-packages/fatslim-0.2.1-py3.6-linux-x86_64.egg/fatslimlib/command.py", line 360, in _run
    output = self.run()
  File "/usr/local/lib/python3.6/dist-packages/fatslim-0.2.1-py3.6-linux-x86_64.egg/fatslimlib/command.py", line 578, in run
    frame_output = self.process_frame(frame)
  File "/usr/local/lib/python3.6/dist-packages/fatslim-0.2.1-py3.6-linux-x86_64.egg/fatslimlib/command.py", line 963, in process_frame
    membrane = membranes[0]
IndexError: list index out of range

Kind Regards,
Chetan

**Comment by lucypham951** [comment]
try reduce the number of frames and see... I got the same problem when I tried to feed 250 frames. But after using trjconv -skip to reduced it to 125 frames, the fatslim run okay.
