### ISSUE TITLE
KeyError: "Atomid not registered in topology:

### ISSUE THREAD

**Issue by katherine1473789695** [FATSLiM/fatslim#19]
Hi, i'm calculating apl and area with my own data, but i met with the following error
Can someone tell me what it means and what should i do? 
 Thanks a lot!

PS: RES is the interacting group name. and the default 'headgroups' is correctly setted. 

Traceback (most recent call last):
  File "/fsa/home/ww_zhangyy/software/anaconda3/envs/mxene/lib/python3.8/site-packages/fatslimlib/__init__.py", line 132
, in main
    exit_code = _command_registry.run(argv)
  File "/fsa/home/ww_zhangyy/software/anaconda3/envs/mxene/lib/python3.8/site-packages/fatslimlib/command.py", line 211,
 in run
    cmd_obj.run_with_args(command_args)
  File "/fsa/home/ww_zhangyy/software/anaconda3/envs/mxene/lib/python3.8/site-packages/fatslimlib/command.py", line 405,
 in run_with_args
    self._run()
  File "/fsa/home/ww_zhangyy/software/anaconda3/envs/mxene/lib/python3.8/site-packages/fatslimlib/command.py", line 477,
 in _run
    nframes = super(AnalyticalCommand, self)._run()
  File "/fsa/home/ww_zhangyy/software/anaconda3/envs/mxene/lib/python3.8/site-packages/fatslimlib/command.py", line 360,
 in _run
    output = self.run()
  File "/fsa/home/ww_zhangyy/software/anaconda3/envs/mxene/lib/python3.8/site-packages/fatslimlib/command.py", line 528,
 in run
    self.initialize_trajetory(traj)
  File "/fsa/home/ww_zhangyy/software/anaconda3/envs/mxene/lib/python3.8/site-packages/fatslimlib/command.py", line 488,
 in initialize_trajetory
    traj.initialize(hg_group=self.namespace.hg_group,
  File "fatslimlib/core_base.pyx", line 1847, in fatslimlib.core_base.Trajectory.initialize
KeyError: "Atomid not registered in topology: 123485. Does group 'RES' from 'b'bilayer_mxene.ndx'' file contains H?"

**Comment by seb-buch** [comment]
Hi,

This may happen when if the index file does not match the actual topology (e.g. water or hydrogens removed after the ndx file was created).
