### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by dandalf02** [FATSLiM/fatslim#6]
Hello,
I am having trouble using the Fatslim. Typically I try something like this:
fatslim apl -c conf.gro -n index_fatslim.ndx --export-apl-raw bilayer_apl.csv

(conf.gro is a file straight from gromacs, 880 POPC molecules in water with ions
index file contains only the 'headgroups' with fosphorus atoms) 

and end up with  this message: 
FATSLiM - Fast Analysis Toolbox for Simulations of Lipid Membranes
version 0.2.1
Copyright (c) 2013-2016 Sébastien Buchoux

Running command: 'apl'... This may take some time, be patient!
Analysis will be performed using 4 threads.

FATAL ERROR: ''

Well, this was unexpected... Congrats, you probably found a bug in FATSLiM!
Please report the following traceback to the devs:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fatslimlib/__init__.py", line 132, in main
    exit_code = _command_registry.run(argv)
  File "/usr/local/lib/python2.7/dist-packages/fatslimlib/command.py", line 211, in run
    cmd_obj.run_with_args(command_args)
  File "/usr/local/lib/python2.7/dist-packages/fatslimlib/command.py", line 405, in run_with_args
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/fatslimlib/command.py", line 477, in _run
    nframes = super(AnalyticalCommand, self)._run()
  File "/usr/local/lib/python2.7/dist-packages/fatslimlib/command.py", line 360, in _run
    output = self.run()
  File "/usr/local/lib/python2.7/dist-packages/fatslimlib/command.py", line 527, in run
    self.verbose)
  File "/usr/local/lib/python2.7/dist-packages/fatslimlib/datareading.py", line 71, in load_trajectory
    readers = get_readers(top_file, index_file, coords_file, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/fatslimlib/datareading.py", line 66, in get_readers
    index_loader(index_file, verbose=verbose), \
  File "fatslimlib/core_base.pyx", line 1280, in fatslimlib.core_base.IndexReader.__init__ (fatslimlib/core_base.c:18308)
    self.load()
  File "fatslimlib/core_base.pyx", line 1288, in fatslimlib.core_base.IndexReader.load (fatslimlib/core_base.c:18521)
    self.fast_load()
  File "fatslimlib/core_datareading.pyx", line 206, in fatslimlib.core_datareading.NdxReader.fast_load (fatslimlib/core_datareading.c:4455)
    groups[last_group] = numpy.fromstring(groups[last_group], dtype=np.int64, sep=" ")
KeyError: ''

Sorry, I made a boo boo...

Is there something obvious I am doing wrong?

**Comment by jinyapan** [comment]
Did u solve this problem ? Because i met the same problem like you.

**Comment by dandalf02** [comment]
Unfortunately no, I gave up on it...

**Comment by seb-buch** [comment]
As for most of the other issues, I have been sitting on this problem for too long because I wanted to rewrite the core code to use mdanalysis. I finally have some time to spend on a proper full rewrite so hopefully this issue will be resolved when issues #7 and #9 are fixed.

**Comment by jonah-lc** [comment]
Hello,
Any updates on this, I seem to hitting a similar error whenever I try to do anything with FATSLiM

"FATAL ERROR: b'headgroups'

Well, this was unexpected... Congrats, you probably found a bug in FATSLiM!
Please report the following traceback to the devs:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fatslim-0.2.2-py3.8-linux-x86_64.egg/fatslimlib/__init__.py", line 132, in main
    exit_code = _command_registry.run(argv)
  File "/usr/local/lib/python3.8/dist-packages/fatslim-0.2.2-py3.8-linux-x86_64.egg/fatslimlib/command.py", line 211, in run
    cmd_obj.run_with_args(command_args)
  File "/usr/local/lib/python3.8/dist-packages/fatslim-0.2.2-py3.8-linux-x86_64.egg/fatslimlib/command.py", line 405, in run_with_args
    self._run()
  File "/usr/local/lib/python3.8/dist-packages/fatslim-0.2.2-py3.8-linux-x86_64.egg/fatslimlib/command.py", line 477, in _run
    nframes = super(AnalyticalCommand, self)._run()
  File "/usr/local/lib/python3.8/dist-packages/fatslim-0.2.2-py3.8-linux-x86_64.egg/fatslimlib/command.py", line 360, in _run
    output = self.run()
  File "/usr/local/lib/python3.8/dist-packages/fatslim-0.2.2-py3.8-linux-x86_64.egg/fatslimlib/command.py", line 528, in run
    self.initialize_trajetory(traj)
  File "/usr/local/lib/python3.8/dist-packages/fatslim-0.2.2-py3.8-linux-x86_64.egg/fatslimlib/command.py", line 488, in initialize_trajetory
    traj.initialize(hg_group=self.namespace.hg_group,
  File "fatslimlib/core_base.pyx", line 1779, in fatslimlib.core_base.Trajectory.initialize
  File "fatslimlib/core_base.pyx", line 1296, in fatslimlib.core_base.IndexReader.__getitem__
KeyError: b'headgroups'

"
